# Generated by Django 4.2 on 2023-07-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_image',
            field=models.ImageField(default=None, null=True, upload_to='recipe'),
        ),
    ]
